In [1]:
import numpy as np

In [2]:
m = np.zeros([10,10])
m

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
m[0] = 1
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
m[-1] = 1
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [9]:
m[: , 0:1] = 1
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
m[: , -1] = 1
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
m2 = np.ones((10,10))
m2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
m2[1:-1, 1:-1] = 0
m2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
m2[: ,:]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
from scipy.sparse import csc_matrix , csr_matrix

In [28]:
m = np.array([[0,1,2,0],[0,0,0,0],[3,5,0,0]])
m

array([[0, 1, 2, 0],
       [0, 0, 0, 0],
       [3, 5, 0, 0]])

In [35]:
print(csr_matrix(m).data)

[1 2 3 5]


In [30]:
print(csc_matrix(m))

  (2, 0)	3
  (0, 1)	1
  (2, 1)	5
  (0, 2)	2


In [36]:
m

array([[0, 1, 2, 0],
       [0, 0, 0, 0],
       [3, 5, 0, 0]])

In [41]:
1 - (np.count_nonzero(m) /m.size)

0.6666666666666667

In [42]:
m.size

12

# Import libraries

In [78]:
import pandas as pd

# Read dataset

In [79]:
df = pd.read_csv("Breast_Cancer.csv")
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842302         M        17.99         10.38          122.80     1001.0   
2      842517         M        20.57         17.77          132.90     1326.0   
3    84300903         M        19.69         21.25          130.00     1203.0   
4    84348301         M        11.42         20.38           77.58      386.1   
..        ...       ...          ...           ...             ...        ...   
568    927241         M        20.60         29.33          140.10     1265.0   
569     92751         B         7.76         24.54           47.92      181.0   
570     92751         B         7.76         24.54           47.92      181.0   
571     92751         B         7.76         24.54           47.92      181.0   
572     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760          0.3001              0.14710   
1            0.11840           0.27760          0.3001              0.14710   
2            0.08474           0.07864          0.0869              0.07017   
3            0.10960           0.15990          0.1974              0.12790   
4            0.14250           0.28390          0.2414              0.10520   
..               ...               ...             ...                  ...   
568          0.11780           0.27700          0.3514              0.15200   
569          0.05263           0.04362          0.0000              0.00000   
570          0.05263           0.04362          0.0000              0.00000   
571          0.05263           0.04362          0.0000              0.00000   
572          0.05263           0.04362          0.0000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          17.33           184.60      2019.0           0.16220   
2    ...          23.41           158.80      1956.0           0.12380   
3    ...          25.53           152.50      1709.0           0.14440   
4    ...          26.50            98.87       567.7           0.20980   
..   ...            ...              ...         ...               ...   
568  ...          39.42           184.60      1821.0           0.16500   
569  ...          30.37            59.16       268.6           0.08996   
570  ...          30.37            59.16       268.6           0.08996   
571  ...          30.37            59.16       268.6           0.08996   
572  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.66560           0.7119                0.2654          0.4601   
2              0.18660           0.2416                0.1860          0.2750   
3              0.42450           0.4504                0.2430          0.3613   
4              0.86630           0.6869                0.2575          0.6638   
..                 ...              ...                   ...             ...   
568            0.86810           0.9387                0.2650          0.4087   
569            0.06444           0.0000                0.0000          0.2871   
570            0.06444           0.0000                0.0000          0.2871   
571            0.06444           0.0000                0.0000          0.2871   
572            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.11890          NaN  
2                    0.08902          NaN  
3                    0.08758          NaN  
4      

# EDA

In [80]:
df.head() 

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842302         M        17.99         10.38          122.80     1001.0   
2    842517         M        20.57         17.77          132.90     1326.0   
3  84300903         M        19.69         21.25          130.00     1203.0   
4  84348301         M        11.42         20.38           77.58      386.1   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.11840           0.27760          0.3001              0.14710   
2          0.08474           0.07864          0.0869              0.07017   
3          0.10960           0.15990          0.1974              0.12790   
4          0.14250           0.28390          0.2414              0.10520   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          17.33           184.60      2019.0            0.1622   
2  ...          23.41           158.80      1956.0            0.1238   
3  ...          25.53           152.50      1709.0            0.1444   
4  ...          26.50            98.87       567.7            0.2098   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.6656           0.7119                0.2654          0.4601   
2             0.1866           0.2416                0.1860          0.2750   
3             0.4245           0.4504                0.2430          0.3613   
4             0.8663           0.6869                0.2575          0.6638   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.11890          NaN  
2                  0.08902          NaN  
3                  0.08758          NaN  
4                  0.17300          NaN  

[5 rows x 33 columns]

In [81]:
df.tail()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
568  927241         M        20.60         29.33          140.10     1265.0   
569   92751         B         7.76         24.54           47.92      181.0   
570   92751         B         7.76         24.54           47.92      181.0   
571   92751         B         7.76         24.54           47.92      181.0   
572   92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
568          0.11780           0.27700          0.3514                0.152   
569          0.05263           0.04362          0.0000                0.000   
570          0.05263           0.04362          0.0000                0.000   
571          0.05263           0.04362          0.0000                0.000   
572          0.05263           0.04362          0.0000                0.000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
568  ...          39.42           184.60      1821.0           0.16500   
569  ...          30.37            59.16       268.6           0.08996   
570  ...          30.37            59.16       268.6           0.08996   
571  ...          30.37            59.16       268.6           0.08996   
572  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
568            0.86810           0.9387                 0.265          0.4087   
569            0.06444           0.0000                 0.000          0.2871   
570            0.06444           0.0000                 0.000          0.2871   
571            0.06444           0.0000                 0.000          0.2871   
572            0.06444           0.0000                 0.000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
568                  0.12400          NaN  
569                  0.07039          NaN  
570                  0.07039          NaN  
571                  0.07039          NaN  
572                  0.07039          NaN  

[5 rows x 33 columns]

In [82]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 573 entries, 0 to 572
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       573 non-null    int64  
 1   diagnosis                573 non-null    object 
 2   radius_mean              573 non-null    float64
 3   texture_mean             573 non-null    float64
 4   perimeter_mean           573 non-null    float64
 5   area_mean                573 non-null    float64
 6   smoothness_mean          573 non-null    float64
 7   compactness_mean         573 non-null    float64
 8   concavity_mean           573 non-null    float64
 9   concave points_mean      573 non-null    float64
 10  symmetry_mean            573 non-null    float64
 11  fractal_dimension_mean   573 non-null    float64
 12  radius_se                573 non-null    float64
 13  texture_se               573 non-null    float64
 14  perimeter_se             5

In [84]:
df.dtypes

id                           int64
diagnosis                   object
radius_mean                float64
texture_mean               float64
perimeter_mean             float64
area_mean                  float64
smoothness_mean            float64
compactness_mean           float64
concavity_mean             float64
concave points_mean        float64
symmetry_mean              float64
fractal_dimension_mean     float64
radius_se                  float64
texture_se                 float64
perimeter_se               float64
area_se                    float64
smoothness_se              float64
compactness_se             float64
concavity_se               float64
concave points_se          float64
symmetry_se                float64
fractal_dimension_se       float64
radius_worst               float64
texture_worst              float64
perimeter_worst            float64
area_worst                 float64
smoothness_worst           float64
compactness_worst          float64
concavity_worst     

In [85]:
df.diagnosis.unique()

array(['M', 'B'], dtype=object)

In [86]:
df.diagnosis.nunique()

2

In [87]:
df.diagnosis.value_counts()

B    360
M    213
Name: diagnosis, dtype: int64

In [88]:
df.diagnosis

0      M
1      M
2      M
3      M
4      M
      ..
568    M
569    B
570    B
571    B
572    B
Name: diagnosis, Length: 573, dtype: object

In [89]:
df.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [92]:
df[df.duplicated()]

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
1    842302         M        17.99         10.38          122.80     1001.0   
570   92751         B         7.76         24.54           47.92      181.0   
571   92751         B         7.76         24.54           47.92      181.0   
572   92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
1            0.11840           0.27760          0.3001               0.1471   
570          0.05263           0.04362          0.0000               0.0000   
571          0.05263           0.04362          0.0000               0.0000   
572          0.05263           0.04362          0.0000               0.0000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
1    ...          17.33           184.60      2019.0           0.16220   
570  ...          30.37            59.16       268.6           0.08996   
571  ...          30.37            59.16       268.6           0.08996   
572  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
1              0.66560           0.7119                0.2654          0.4601   
570            0.06444           0.0000                0.0000          0.2871   
571            0.06444           0.0000                0.0000          0.2871   
572            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
1                    0.11890          NaN  
570                  0.07039          NaN  
571                  0.07039          NaN  
572                  0.07039          NaN  

[4 rows x 33 columns]

In [100]:
df[df["radius_mean"] > 20].head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
2     842517         M        20.57         17.77           132.9     1326.0   
5   84358402         M        20.29         14.34           135.1     1297.0   
24    851509         M        21.16         23.04           137.2     1404.0   
79   8610862         M        20.18         23.97           143.7     1245.0   
83   8611555         M        25.22         24.91           171.5     1878.0   

    smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
2           0.08474           0.07864          0.0869              0.07017   
5           0.10030           0.13280          0.1980              0.10430   
24          0.09428           0.10220          0.1097              0.08632   
79          0.12860           0.34540          0.3754              0.16040   
83          0.10630           0.26650          0.3339              0.18450   

    ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
2   ...          23.41            158.8      1956.0            0.1238   
5   ...          16.67            152.2      1575.0            0.1374   
24  ...          35.59            188.0      2615.0            0.1401   
79  ...          31.72            170.3      1623.0            0.1639   
83  ...          33.62            211.7      2562.0            0.1573   

    compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
2              0.1866           0.2416                0.1860          0.2750   
5              0.2050           0.4000                0.1625          0.2364   
24             0.2600           0.3155                0.2009          0.2822   
79             0.6164           0.7681                0.2508          0.5440   
83             0.6076           0.6476                0.2867          0.2355   

    fractal_dimension_worst  Unnamed: 32  
2                   0.08902          NaN  
5                   0.07678          NaN  
24                  0.07526          NaN  
79                  0.09964          NaN  
83                  0.10510          NaN  

[5 rows x 33 columns]

In [110]:
# (df["radius_mean"] > 20) and (df["radius_mean"] < 25)

In [114]:
df2 = pd.DataFrame([[1, 444, 'abc'],
                   [2, 555, 'def'],
                   [3, 666, 'ghi'],
                   [4, 444, 'xyz']] ,columns=["col1" ,"col2" , "col3"])

df2

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [117]:
df3 = pd.DataFrame({"key1":[23,32,25] , "key2":["A" , "B" , "C"]} , index = ["W" ,"X" , "Y"])

In [118]:
df3

key1 key2
W    23    A
X    32    B
Y    25    C

In [129]:
df2 = pd.get_dummies(df2 )

In [130]:
df2

col1  col2  col3_abc  col3_def  col3_ghi  col3_xyz
0     1   444         1         0         0         0
1     2   555         0         1         0         0
2     3   666         0         0         1         0
3     4   444         0         0         0         1