In [1]:
import numpy as np 

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.mean(arr)

5.5

In [4]:
m = np.array([[1,2,3,4,5],[1,2,3,4,5]])
m

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [6]:
# m.shape

In [8]:
np.mean(m , axis = 0)

array([1., 2., 3., 4., 5.])

In [9]:
np.mean(m , axis = 1)

array([3., 3.])

In [10]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.var(arr)

8.25

In [12]:
a = np.array([1,2,3])

In [13]:
np.var(a)

0.6666666666666666

In [14]:
np.std(a)

0.816496580927726

In [15]:
394 - 147

247

In [16]:
394 + 147

541