In [4]:
import numpy as np

In [6]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__packag

In [8]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])

In [9]:
arr1.dtype

dtype('int32')

In [11]:
arr1.shape

(9,)

In [12]:
len(arr1)

9

In [25]:
np.empty([3,3])

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [2.78147304e-307, 1.42413555e-306, 1.78019082e-306],
       [1.37959740e-306, 2.29178686e-312, 1.29516345e-318]])

In [23]:
z= np.zeros([3,4])

In [24]:
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [43]:
from numpy import ones

In [44]:
ones(6)

array([1., 1., 1., 1., 1., 1.])

In [45]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionad

In [46]:
np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

In [52]:
a1 = np.array([1,2,3,4])
a2 = np.array([1,2,3,4])
a3 = np.vstack((a1,a2))
a3

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [53]:
a1 = np.array([1,2,3])
a2 = np.array([1,2,3,4])
a3 = np.hstack((a1,a2))
a3

array([1, 2, 3, 1, 2, 3, 4])

In [56]:
m = np.array([[1,2,3],[3,3,4],[3,4,5]])
m

array([[1, 2, 3],
       [3, 3, 4],
       [3, 4, 5]])

In [58]:
m[-1]

array([3, 4, 5])

In [59]:
m[ : , : ]

array([[1, 2, 3],
       [3, 3, 4],
       [3, 4, 5]])

In [67]:
m[: , 0:2]

array([[1, 2],
       [3, 3],
       [3, 4]])

In [69]:
m[ : , -1:]

array([[3],
       [4],
       [5]])

In [72]:
m[0:2 , :]

array([[1, 2, 3],
       [3, 3, 4]])

In [73]:
m

array([[1, 2, 3],
       [3, 3, 4],
       [3, 4, 5]])

In [74]:
m[1:2 , 1:2]

array([[3]])

In [75]:
m[1,1]

3

In [76]:
m[2,2]

5

In [78]:
ds = np.array([[1,2,3,4,0],[1,2,3,4,1],
              [1,2,3,4,0],[1,2,5,4,1],
               [1,2,8,4,0],[1,2,5,4,1]])
ds

array([[1, 2, 3, 4, 0],
       [1, 2, 3, 4, 1],
       [1, 2, 3, 4, 0],
       [1, 2, 5, 4, 1],
       [1, 2, 8, 4, 0],
       [1, 2, 5, 4, 1]])

In [80]:
x = ds[:, :-1]
x

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 5, 4],
       [1, 2, 8, 4],
       [1, 2, 5, 4]])

In [82]:
y = ds[:,-1:]
y

array([[0],
       [1],
       [0],
       [1],
       [0],
       [1]])

In [86]:
x_train = x[0:4 , :]

In [88]:
x_test = x[4: ]

In [89]:
y_train = y[0:4 , :]
y_train

array([[0],
       [1],
       [0],
       [1]])

In [91]:
y_test = y[4: ]
y_test

array([[0],
       [1]])

In [92]:
len(ds)

6

In [94]:
percent = 60
train_rows = int((len(ds) * percent)/ 100)  
train_rows

3

In [95]:
x = ds[:, :-1]


In [96]:
y = ds[:,-1:]
y

array([[0],
       [1],
       [0],
       [1],
       [0],
       [1]])

In [98]:
x[0:train_rows]

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [99]:
x[train_rows : ]

array([[1, 2, 5, 4],
       [1, 2, 8, 4],
       [1, 2, 5, 4]])

In [100]:
y[0:train_rows]

array([[0],
       [1],
       [0]])

In [101]:
y[train_rows:]

array([[1],
       [0],
       [1]])

In [102]:
def train_test_split(data , percent):
    train_rows = int((len(data) * percent)/ 100) 
    x = data[:,:-1]
    y = data[:,-1:]
    x_train,x_test = x[0:train_rows] , x[train_rows:]
    y_train,y_test = y[0:train_rows] , y[train_rows:]
    return x_train , x_test , y_train , y_test 

In [106]:
x_train , x_test , y_train , y_test = train_test_split(ds , 70)

In [107]:
print("x_train is \n" , x_train)
print("x_test is \n" , x_test)
print("y_train is \n" , y_train)
print("y_test is \n" , y_test)

x_train is 
 [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 5 4]]
x_test is 
 [[1 2 8 4]
 [1 2 5 4]]
y_train is 
 [[0]
 [1]
 [0]
 [1]]
y_test is 
 [[0]
 [1]]


In [109]:
a = np.arange(1,10)

In [110]:
a.reshape([3,3])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
a.reshape((len(a),1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [112]:
len(a)

9

In [115]:
a = np.arange(0,20)

In [116]:
len(a)

20

In [121]:
m=a.reshape([4,5])

In [122]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [124]:
m * m

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361]])

In [125]:
m = np.array([[1,2,3],[3,3,4],[3,4,5]])
m

array([[1, 2, 3],
       [3, 3, 4],
       [3, 4, 5]])

In [126]:
m2 = np.array([[2,2,3],[3,4,4],[1,4,5]])
m2

array([[2, 2, 3],
       [3, 4, 4],
       [1, 4, 5]])

In [127]:
m.shape

(3, 3)

In [128]:
m2.shape

(3, 3)

In [129]:
m.dot(m2)

array([[11, 22, 26],
       [19, 34, 41],
       [23, 42, 50]])

In [130]:
m2.dot(m)

array([[17, 22, 29],
       [27, 34, 45],
       [28, 34, 44]])

In [140]:
a = np.array([1,2,3])
a3 = a.reshape((len(a),1))
a3

array([[1],
       [2],
       [3]])

In [141]:
m +  a3

array([[2, 3, 4],
       [5, 5, 6],
       [6, 7, 8]])

In [134]:
a + m

array([[2, 4, 6],
       [4, 5, 7],
       [4, 6, 8]])

In [136]:
a2 = np.array([1,2])
a

array([1, 2, 3])

In [138]:
m + a2

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [142]:
m

array([[1, 2, 3],
       [3, 3, 4],
       [3, 4, 5]])

In [143]:
np.tril(m)

array([[1, 0, 0],
       [3, 3, 0],
       [3, 4, 5]])

In [144]:
np.triu(m)

array([[1, 2, 3],
       [0, 3, 4],
       [0, 0, 5]])

In [149]:
np.diag(m)
np.diag(m, k=-1)

array([3, 4])

In [147]:
help(np.diag)

Help on function diag in module numpy:

diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    
    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.
    
    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.
    
    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.
    
    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array with the flattened input 

In [151]:
m2 = np.array([[2,2,3],[3,4,4],[1,4,5],[1,4,5]])

In [152]:
m2

array([[2, 2, 3],
       [3, 4, 4],
       [1, 4, 5],
       [1, 4, 5]])

In [158]:
d = np.diag(m2 )

In [159]:
np.diag(d)

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

In [160]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [161]:
m

array([[1, 2, 3],
       [3, 3, 4],
       [3, 4, 5]])

In [162]:
m.T

array([[1, 3, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [163]:
np.trace(m)

9

In [ ]:
lst = 