In [11]:
m1 = [[1,2],
      [2,3],
      [3,4]]
m2 = [[3,4],
      [4,5],
      [5,6]]
res = [[0,0],[0,0],[0,0]]

In [15]:
for i in range(len(m1)):
    for j in range(len(m2[0])):
        res[i][j] = m1[i][j] + m2[i][j]
        
for i in res:
    print(i)

[4, 6]
[6, 8]
[8, 10]


In [17]:
v1 = [1,2,3]
v2 = [2,3,4]
def add(w1 , w2):
    res = []
    if len(w1) == len(w2):
        for i in range(len(w1)):
            res.append(w1[i] + w2[i])
    return res

In [18]:
add(v1,v2)

[3, 5, 7]

In [19]:
[i + x for i , x in zip(v1,v2) ]

[3, 5, 7]

In [25]:
lst = [i + x for i , x in zip(v1,v2)] if len(v1) == len(v2) else print(False)

In [26]:
lst

[3, 5, 7]

In [31]:
# list(map(lambda x : x*2 , v1))

In [33]:
v1 = [1,2,3]
v2 = [2,3,4,3]
try:
    assert len(v1) == len(v2)
except:
    print("erorrrrrrrrrrr")

erorrrrrrrrrrr


In [34]:
assert len(v1) == len(v2) , "error"

AssertionError: error

In [44]:
def summ(n1,n2):
#     n3 = n1+n2/2
    def add(n1,n2,n3=1):
        return n1+n2+n3
    return add(n1,n2)
    

In [51]:
summ(1.5678745678,2)

4.5678745678

In [54]:
v1 = [1,2,3]
v2 = [4,5,6]
lst = []
for i in range(len(v1)):
    lst.append( v1[i] * v2[i] )
print(lst)
print(sum(lst))

[4, 10, 18]
32


In [60]:
m1 = [[1,2],
      [2,3],
      [3,4]]
m2 = [[3,4],
      [4,5]]
[[sum(i*x for i , x in zip(row,col)) for col in zip(*m2)] for row in m1]

[[11, 14], [18, 23], [25, 32]]

In [70]:
m1 = [[1,2],
      [2,3],
      [3,4]]
m2 = [[3,4],
      [4,5]]

In [72]:
[[sum( i * x for i , x in zip(row , col )) for col in zip(*m2)]  for row in m1]

[[11, 14], [18, 23], [25, 32]]

In [73]:
import numpy as np 
m1 = [[1,2],
      [2,3],
      [3,4]]
m2 = [[3,4],
      [4,5]]
m1_arr = np.array(m1)
m2_arr = np.array(m2)

In [74]:
m1_arr

array([[1, 2],
       [2, 3],
       [3, 4]])

In [78]:
m2_arr

array([[3, 4],
       [4, 5]])

In [79]:
m1_arr.dot(m2_arr)

array([[11, 14],
       [18, 23],
       [25, 32]])

In [81]:
m1 = [[1,2],
      [2,3],
      [3,4]]
m2 = [[3,4],
      [4,5],
      [5,6]]
m1_arr = np.array(m1)
m2_arr = np.array(m2)

In [83]:
m1_arr * m2_arr

array([[ 3,  8],
       [ 8, 15],
       [15, 24]])

In [84]:
class Computation:
    def __init__ (self):
        pass
# --- Factorial ------------
    def factorial(self, n):
        j = 1
        for i in range (1, n + 1):
            j = j * i
        return j
    
# --- Sum of the first n numbers ----
    def sum (self, n):
        j = 1
        for i in range (1, n + 1):
            j = j + i
        return j
    
# --- Primality test of a number ------------
    def testPrim (self, n):
        j = 0
        for i in range (1, n + 1):
            if (n% i == 0):
                j = j + 1
        if (j == 2):
            return True
        else:
            return False

# --- Primality test of two integers ------------
    def testprims (self, n, m):
        
        # initialize the number of commons divisors
        commonDiv = 0
        for i in range (1, n + 1):
            if (n% i == 0 and m% i == 0):
                commonDiv = commonDiv + 1
        if commonDiv == 1:
            print ("The numbers", n, "and", m, "are co-primes")
        else:
            print ("The numbers", n, "and", m, "are not co-primes")

#---Multiplication table-------------
    def tableMult (self, k):
        for i in range (1,10):
            print (i, "x", k, "=", i * k)

# --- All multiplication tables of the numbers 1, 2, .., 9
    def allTables (self):
        for k in range (1,10):
            print ("nthe multiplication table of:", k, "is:")
            for i in range (1,10):
                print (i, "x", k, "=", i * k)

# ----- list of divisors of an integer
    def listDiv (self, n):
        # initialization of the list of divisors
        lDiv = []
        for i in range (1, n + 1):
            if (n% i == 0):
                lDiv.append(i)
        return lDiv

# ------ list of prime divisors of an integer ----------------
    def listDivPrim (self, n):
        # initialization of the list of divisors
        lDiv = []
        for i in range (1, n + 1):
            if (n% i == 0 and self.testPrim (i)):
                lDiv.append (i)
        return lDiv

# Instantiation example
Comput= Computation ()
Comput.testprims (13, 7)
print ("List of divisors of 18:", Comput.listDiv (18))
print ("List of prime divisors of 18:", Comput.listDivPrim (18))
Comput.allTables ()

The numbers 13 and 7 are co-primes
List of divisors of 18: [1, 2, 3, 6, 9, 18]
List of prime divisors of 18: [2, 3]
nthe multiplication table of: 1 is:
1 x 1 = 1
2 x 1 = 2
3 x 1 = 3
4 x 1 = 4
5 x 1 = 5
6 x 1 = 6
7 x 1 = 7
8 x 1 = 8
9 x 1 = 9
nthe multiplication table of: 2 is:
1 x 2 = 2
2 x 2 = 4
3 x 2 = 6
4 x 2 = 8
5 x 2 = 10
6 x 2 = 12
7 x 2 = 14
8 x 2 = 16
9 x 2 = 18
nthe multiplication table of: 3 is:
1 x 3 = 3
2 x 3 = 6
3 x 3 = 9
4 x 3 = 12
5 x 3 = 15
6 x 3 = 18
7 x 3 = 21
8 x 3 = 24
9 x 3 = 27
nthe multiplication table of: 4 is:
1 x 4 = 4
2 x 4 = 8
3 x 4 = 12
4 x 4 = 16
5 x 4 = 20
6 x 4 = 24
7 x 4 = 28
8 x 4 = 32
9 x 4 = 36
nthe multiplication table of: 5 is:
1 x 5 = 5
2 x 5 = 10
3 x 5 = 15
4 x 5 = 20
5 x 5 = 25
6 x 5 = 30
7 x 5 = 35
8 x 5 = 40
9 x 5 = 45
nthe multiplication table of: 6 is:
1 x 6 = 6
2 x 6 = 12
3 x 6 = 18
4 x 6 = 24
5 x 6 = 30
6 x 6 = 36
7 x 6 = 42
8 x 6 = 48
9 x 6 = 54
nthe multiplication table of: 7 is:
1 x 7 = 7
2 x 7 = 14
3 x 7 = 21
4 x 7 = 28
5 x 7 = 35
6 x 